import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  static Future<void> generateAndShareGatePass({
    required String visitorName,
    required String validFrom,
    required String validTo,
    required String purpose,
    required String passId,
    required String societyName,
  }) async {
    final pdf = pw.Document();

    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(
          base: font,
          bold: fontBold,
        ),
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Container(
              width: 350,
              height: 550,
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.blue900, width: 3),
                borderRadius: pw.BorderRadius.circular(16),
                color: PdfColors.white,
              ),
              child: pw.Column(
                mainAxisAlignment: pw.MainAxisAlignment.start,
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  // Header
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.all(16),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.blue900,
                      borderRadius: const pw.BorderRadius.vertical(top: pw.Radius.circular(13)),
                    ),
                    child: pw.Column(
                      children: [
                        pw.Text(
                          societyName,
                          style: pw.TextStyle(color: PdfColors.white, fontSize: 24, fontWeight: pw.FontWeight.bold),
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'OFFICIAL GATE PASS',
                          style: pw.TextStyle(color: PdfColors.white, fontSize: 16, letterSpacing: 2),
                        ),
                      ],
                    ),
                  ),
                  
                  pw.SizedBox(height: 24),
                  
                  // QR Code
                  pw.Container(
                    padding: const pw.EdgeInsets.all(8),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey300),
                      borderRadius: pw.BorderRadius.circular(8),
                    ),
                    child: pw.BarcodeWidget(
                      color: PdfColors.black,
                      barcode: pw.Barcode.qrCode(),
                      data: 'RESIFLOW:PASS:$passId',
                      width: 150,
                      height: 150,
                    ),
                  ),
                  
                  pw.SizedBox(height: 16),
                  pw.Text('SCAN AT GATE', style: pw.TextStyle(color: PdfColors.grey700, fontSize: 12, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 24),
                  
                  // Details
                  pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 32),
                    child: pw.Column(
                      children: [
                        _buildDetailRow('VISITOR NAME', visitorName.toUpperCase()),
                        pw.Divider(color: PdfColors.grey300),
                        _buildDetailRow('PASS ID', passId),
                        pw.Divider(color: PdfColors.grey300),
                        _buildDetailRow('PURPOSE', purpose.toUpperCase()),
                        pw.Divider(color: PdfColors.grey300),
                        _buildDetailRow('VALIDITY', '$validFrom TO $validTo'),
                      ],
                    ),
                  ),
                  
                  pw.Spacer(),
                  
                  // Footer
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.all(12),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.grey200,
                      borderRadius: const pw.BorderRadius.vertical(bottom: pw.Radius.circular(13)),
                    ),
                    child: pw.Text(
                      'Generated by ResiFlow System\nThis pass is non-transferable.',
                      textAlign: pw.TextAlign.center,
                      style: pw.TextStyle(color: PdfColors.grey700, fontSize: 10),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );

    // Use sharePdf which works better across Web and Mobile
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'GatePass_$passId.pdf',
    );
  }

  static pw.Widget _buildDetailRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(color: PdfColors.grey600, fontSize: 12, fontWeight: pw.FontWeight.bold)),
          pw.Text(value, style: pw.TextStyle(color: PdfColors.black, fontSize: 14, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
